# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
pinv <- function(V, tol = 1.e-6) {
    .Call(`_FastMath_pinv`, V, tol)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_FastMath_RcppExport_registerCCallable', PACKAGE = 'FastMath')
})
